---
# tasks file for filebeat_configure
- name: Filebeat configuration for jenkins
  template:
    src: ../templates/jenkins/filebeat.yml
    dest: /etc/filebeat
  when: inventory_hostname == "jenkins"
- name: Filebeat configuration for elk
  template:
    src: ../templates/elk/filebeat.yml
    dest: /etc/filebeat
  when: inventory_hostname == "elk-server"
- name: Filebeat configuration for nexus
  template:
    src: ../templates/nexus/filebeat.yml
    dest: /etc/filebeat
  when: inventory_hostname == "nexus-machine"
- name: Filebeat configuration for apache
  template:
    src: ../templates/apache/filebeat.yml
    dest: /etc/filebeat
  when: inventory_hostname == "apache-server"
- name: Filebeat configuration for zabbix
  template:
    src: ../templates/zabbix/filebeat.yml
    dest: /etc/filebeat
  when: inventory_hostname == "zabbix-server"
- name: Filebeat configuration for sonarqube
  template:
    src: ../templates/sonarqube/filebeat.yml
    dest: /etc/filebeat
  when: inventory_hostname == "sonar-server"
- name: Filebeat configuration for maven
  template:
    src: ../templates/maven/filebeat.yml
    dest: /etc/filebeat
  when: inventory_hostname == "maven-server"

- name: ensure filebeat is running
  systemd: state=restarted name=filebeat

