---
- hosts: nexus-machine
  become: yes
  vars_files:
        - ./vars/main.yml
  roles:
  - ./roles/filebeat_configure
- hosts: elk-server
  become: yes
  vars_files:
        - ./vars/main.yml
  roles:
  - ./roles/nexus_syslog
- hosts: logstash-server
  become: yes
  vars_files:
        - ./vars/main.yml
  roles:
  - ./roles/logstash_configure

