- name: Playbook
  hosts: test
  become: yes
  become_user: root
  tasks:
       - name: Install repos
         become: yes
         command: rpm -Uvh https://repo.zabbix.com/zabbix/6.2/rhel/9/x86_64/zabbix-release-6.2-3.el9.noarch.rpm
       - name: install agent
         dnf:
           name: zabbix-agent
           state: present
       - name: restart  service
         become: yes
         command: "systemctl restart zabbix-agent"
       - name: enable  service
         become: yes
         command: "systemctl enable zabbix-agent"

           # - name: add port
         #ansible.builtin.lineinfile:
           # path: /etc/zabbix/zabbix_agentd.conf
            # regexp: '#ListenPort=10050'
            # line: ListenPort=10050
            # - name: server
         #ansible.builtin.lineinfile:
           #path: /etc/zabbix/zabbix_agentd.conf
            #regexp: '#Server=3.108.45.125'
            #line: Server=3.108.45.125
            #- name: serveractive
         # ansible.builtin.lineinfile:
           # path: /etc/sysctl.conf
            # regexp: '#ServerActive=3.108.45.125'
            #   line: ServerActive=3.108.45.125
            # - name: restart  service
         #  become: yes
           # command: "systemctl restart zabbix-agent"
